<<<<<<< HEAD
our_read_order:
    resource: "@OurReadOrderBundle/Controller/"
    type:     annotation
    prefix:   /

order:
    resource: "@OrderBundle/Controller/"
    type:     annotation
    prefix:   /

=======
>>>>>>> 5059f3a6c7e3eb9dfb4f5e25a779835f42e132ec
remote_library:
    resource: "@RemoteLibraryBundle/Resources/config/routing.yml"
    prefix:   /

our:
    resource: "@OurBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

library:
    resource: "@LibraryBundle/Resources/config/routing.yml"
    prefix:   /