remote_library:
    resource: "@RemoteLibraryBundle/Resources/config/routing.yml"
    prefix:   /

our:
    resource: "@OurBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
