services:
    cover_uploader:
        class: OurRead\LibraryBundle\Services\BookCoverService\BookCoverUploader
    cover_remover:
        class: OurRead\LibraryBundle\Services\BookCoverService\BookCoverRemover
