OurHomepage:
    path:     /
    defaults: { _controller: OurBundle:MainPage:index }
BookPage:
    path:     /book/{id}
    defaults: { _controller: OurBundle:BookPage:index }
UserPage:
    path:     /user
    defaults: { _controller: OurBundle:UserPage:index }
MyBooksPage:
    path:     /mybooks
    defaults: { _controller: OurBundle:MyBooksPage:index }
CategoriesPage:
    path:     /categories
    defaults: { _controller: OurBundle:CategoriesPage:index }