OurHomepage:
    path:     /
    defaults: { _controller: OurBundle:MainPage:index }
BookPage:
    path:     /book/{id}
    defaults: { _controller: OurBundle:BookPage:index }
BooksPage:
    path:     /books
    defaults: { _controller: OurBundle:BooksPage:index }
UserPage:
    path:     /user
    defaults: { _controller: OurBundle:UserPage:index }
DeleteBook:
    path:     /user/delete/{id}
ConfirmOrder:
    path:     /confirm/{id}
    defaults: { _controller: OurBundle:UserPage:confirm }
CancelOrder:
    path:     /cancel/{id}
    defaults: { _controller: OurBundle:UserPage:cancel }

MyBooksPage:
    path:     /mybooks
    defaults: { _controller: OurBundle:MyBooksPage:index }
CategoriesPage:
    path:     /categories
    defaults: { _controller: OurBundle:CategoriesPage:index }
acttco:
    path:     /contact
    defaults: { _controller: OurBundle:Contact:contact }
AddBook:
    path:     /addBook
    defaults: { _controller: OurBundle:AddBook:addBook }
SearchResult:
    path:     /searchResult
    defaults: { _controller: OurBundle:SearchResult:searchResult }
CreateOrder:
    path:     /order/{id}
    defaults: { _controller: OurBundle:Order:createOrder }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
ExtendOrder:
    path:     /extend/{id}
    defaults: { _controller: OurBundle:Order:extendOrder }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
Reservation:
    path:     /reserve/{id}
    defaults: { _controller: OurBundle:Order:reserveBook }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
Return:
    path:     /return/{id}
    defaults: { _controller: OurBundle:Order:returnBook }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
CancelReservation:
    path:     /cancel/{id}
    defaults: { _controller: OurBundle:Order:cancelReservation }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
CancelAndOrder:
    path:     /cancelAndOrder/{id}
    defaults: { _controller: OurBundle:Order:cancelAndOrder }
    condition: "request.headers.get('X-Requested-With') == 'XMLHttpRequest'"
