services:
    create_order:
          class: OurRead\OrderBundle\Services\CreateOrderService
          arguments:
              - @doctrine
    check_book_availability:
          class: OurRead\OrderBundle\Services\BookAvailabilityService
          arguments:
              - @doctrine
    extend_order:
          class: OurRead\OrderBundle\Services\OrderProlongationService
          arguments:
              - @doctrine
    reserve_book:
          class: OurRead\OrderBundle\Services\BookReservationService
          arguments:
              - @doctrine
    return_book:
          class: OurRead\OrderBundle\Services\ReturnBookService
          arguments:
              - @doctrine
    cancel_reservation:
          class: OurRead\OrderBundle\Services\CancelReservationService
          arguments:
              - @doctrine
